accounts/urls.py
from django.urls import include, path

from . import views
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url="login/", permanent=False)),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.profile),   
    path('bye/', views.bye), #logout destination 
]

api/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url="surveys/", permanent=False) ),
    path('surveys/', views.SurveyList.as_view()),
    path('surveys/<int:pk>/', views.SurveyDetail.as_view()),
    path('surveys/add/', views.SurveyAdd.as_view()),
    path('questions/<int:pk>/', views.QuestionDetail.as_view()),
    path('questions/add/', views.QuestionAdd.as_view()),
    path('answers/<int:pk>/', views.AnswerDetail.as_view()),
    path('answers/add/', views.AnswerAdd.as_view())
]

surveys/urls.py
from django.urls import path

from . import views

#name for cross-linking from other apps
app_name='surveys'

urlpatterns = [
    path('add/', views.add, name="add_survey"),
    path('<int:survey_id>/', views.detail, name='detail'),
    path('<int:survey_id>/delete', views.delete, name='delete'),
    path('<int:survey_id>/edit_survey', views.edit_survey, name='edit_survey'),
    #path('<int:survey_id>/edit_questions', views.edit_questions, name='edit_questions') #broken
]

surveything/urls.py
#top-level urls

from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('surveys/', include('surveys.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url="accounts/login", permanent=False))
]

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

from surveys.models import Survey


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

def bye(request):
    return HttpResponse("Bye!")

def profile(request):
    template_name = 'accounts/profile.html'
    surveys_list = Survey.objects.filter(author_id=request.user.id)
    context = {
        'surveys_list': surveys_list,
    }

    return render(request, template_name, context)

templates/accounts/profile.html
{% extends '../base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<p><a href="{% url 'surveys:add_survey' %}">Add a survey</a></p>
{% if surveys_list %}
    <table class="table">
        <thead class="thead-dark">
            <th>Survey name</th>
            <th></th>
            <th></th>
            <th></th>
        </thead>
    {% for survey in surveys_list %}
        <tr>
            <td>
                <h4><a href="{% url 'surveys:detail' survey.id %}">{{ survey.title }}</a></h6>
            </td>
            <td>
                <a href="{% url 'surveys:edit_survey' survey.id %}" class="btn btn-primary btn-warning">Edit survey body</a>
            </td>
            <td>
                <a href="/api/surveys/{{survey.id}}/?format=json" class="btn btn-primary btn-info">JSON</a>
            </td>
            <td>
                <form method="POST" action="{% url 'surveys:delete' survey.id %}">
                    {% csrf_token %}
                    <button type='submit' class="btn btn-primary btn-danger">delete</button>
                </form>
                
            </td>
          
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No surveys are available.</p>
{% endif %}

{% endblock %}